graphite_url: http://localhost
hosts:
  exclude:
    - carbon
metrics:
  baseline:
    - df.root.df_complex.free.value
    - df.mnt.df_complex.free.value
    - disk.xvda1.disk_octets.{read,write}
    - disk.xvdb.disk_octets.{read,write}
    - interface.if_octets.eth0.{rx,tx}
    - load.load.{shortterm,midterm,longterm}
    - memory.memory.free.value
  disk:
    - df.*.df_complex.free.value
    - disk.*.disk_octets.{read,write}
