graphite_urls:
  internal: http://localhost
  external: https://monitor2.whiskeymedia.com
hosts:
  exclude:
    - carbon
  default_metrics:
    - df.root.df_complex.free.value
    - df.mnt.df_complex.free.value
    - disk.xvda1.disk_octets.{read,write}
    - disk.xvdb.disk_octets.{read,write}
    - interface.if_octets.eth0.{rx,tx}
    - load.load.{shortterm,midterm,longterm}
    - memory.memory.free.value
