graphite_uri: http://localhost:8081
hosts:
  exclude:
    - carbon
defaults:
  height: 250
  width: 400
  from: -4hours
periods:
  recent: -4hours
  day: -24hours
  week: -7days
metrics:
  free_disk_space:
    path: df.*.df_complex.free.value
    exclude: [dev, dev-shm, var-lock, var-run]
    expand: all
groups:
  baseline:
    - free_disk_space
    - disk.xvda1.disk_octets.{read,write}
    - disk.xvdb.disk_octets.{read,write}
    - interface.if_octets.eth0.{rx,tx}
    - load.load.*
    - memory.memory.free.value
  disk:
    - free_disk_space
    - disk.{xvda1,xvdb,xvdf}.disk_octets.{read,write}
  cpu:
    - load.load.*
  network:
    - interface.if_octets.eth0.{rx,tx}
