graphite_uri: http://localhost
hosts:
  exclude:
    - carbon
defaults:
  height: 250
  width: 400
  from: -4hours
periods:
  recent: -4hours
  day: -24hours
  week: -7days
metrics:
  free_disk_space:
    path: df.*.df_complex.free.value
    exclude: [dev, dev-shm, var-lock, var-run]
    expand: all
groups:
  baseline:
    - free_disk_space
    - disk.xvda1.disk_octets.{read,write}
    - disk.xvdb.disk_octets.{read,write}
    - interface.if_octets.eth0.{rx,tx}
    - load.load.*
    - memory.memory.free.value
  disk:
    - free_disk_space
    - disk.{xvda1,xvdb,xvdf}.disk_octets.{read,write}
  cpu:
    - load.load.*
  network:
    - interface.if_octets.eth0.{rx,tx}
collections:
  by_project:
    title: "By project"
    groups:
      animevice:
        - cache10.whiskeymedia.com
        - cache11.whiskeymedia.com
        - chat1.whiskeymedia.com
        - chat2.whiskeymedia.com
        - chat3.whiskeymedia.com
        - db.animevice.com
        - haproxy1.whiskeymedia.com
        - haproxy2.whiskeymedia.com
        - lb2.whiskeymedia.com
        - lb3.whiskeymedia.com
        - redis10.whiskeymedia.com
        - redis11.whiskeymedia.com
        - search1.whiskeymedia.com
        - search2.whiskeymedia.com
        - web5.whiskeymedia.com
        - web6.whiskeymedia.com
        - web7.whiskeymedia.com
        - web8.whiskeymedia.com
      giantbomb:
        - celery2.giantbomb.com
        - chat1.whiskeymedia.com
        - chat2.whiskeymedia.com
        - chat3.whiskeymedia.com
        - db.giantbomb.com
        - lb2.whiskeymedia.com
        - lb3.whiskeymedia.com
        - redis10.whiskeymedia.com
        - redis11.whiskeymedia.com
        - search1.whiskeymedia.com
        - search2.whiskeymedia.com
        - web1.giantbomb.com
        - web10.giantbomb.com
        - web2.giantbomb.com
        - web3.giantbomb.com
        - web4.giantbomb.com
        - web8.giantbomb.com
        - web9.giantbomb.com
